### ISSUE TITLE
LegacyUI chooseFile has extension problems when saving

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#101]
If the `JFileChooser` is enabled, saving - e.g. via `File > Export > Image...` - works fine: what you see as a file name and extension is what you get.

If `JFileChooser` is disabled however, strange things happen.

For example, the `.ome.tif` extension gets converted to `.ometif`. This makes it impossible to save a `.ome.tif` as an `.ome.tif`.

A partial fix is to pass `null` as the extension to the ImageJ 1.x `SaveDialog`. This works OK when the `JFileChooser` is disabled - although you then have to manually type in the extension.

But when a `null` extension is passed with the `JFileChooser` enabled, even if an extension is specified, it gets truncated (e.g. `.ome.tif` gets saved as `.ome`).

Best solution I can think of is to check if `JFileChooser` is enabled and pass the extension, or `null` if it's not.

**Comment by hinerm** [comment]
Note that `JFIleChooser` can be toggled via `Edit > Options > Input/Output... > Use JFileChooser to open/save`

**Comment by hinerm** [comment]
after some investigation I think we also have to skip the `FileUtils` extension getter and instead manually use the first instance of `'.'` when using `JFileChooser`, as it seems like that's what IJ1 expects. Still testing though.

**Comment by hadim** [comment]
+1 (useless comment to get notified by mail)
