### ISSUE TITLE
Refactor ImagePlus/ImageDisplay harmonizers to be wrapping adapters

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#105]
The `LegacyImageMap` copies pixel data to convert between `ImagePlus` and `ImageDisplay`. This hurts performance and can not possibly scale to large datasets. We should be using lightweight adapter classes that extend the appropriate interfaces and pass through to wrapped data. This way there is no concern over de-synchronization, translation costs, etc...

**Comment by ctrueden** [comment]
This is a duplicate(-ish) of #86.

**Comment by ctrueden** [comment]
See also #182.
