### ISSUE TITLE
Macro recorder doesn't support SciJava script languages

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#122]
It would be really cool if it did!

**Comment by hinerm** [comment]
Pointed out by @jwarrick

**Comment by ctrueden** [comment]
It's true! scijava/scijava-common#57

**Comment by ctrueden** [comment]
And I guess the other piece of this would a new "Script Recorder" UI component, which would replace Image1's Macro Recorder. I filed an issue: scijava/scijava-ui-swing#15
