### ISSUE TITLE
ImagePlus from Dataset conversion issue

### ISSUE THREAD

**Issue by hadim** [imagej/imagej-legacy#138]
Since I have difficulties to use `ImageDisplay.setPosition()` using IJ2 interface (see https://github.com/imagej/imagej/issues/140) I try to do it with the IJ1 API.

While I can successfully convert a `Dataset` to an `ij.ImagePlus`, methods such as `setSlice()` does not work on  `ij.ImagePlus`whereas it's working fine using the `ij.ImagePlus` from Python annotations.

See the following code : 

```python
# @Dataset data
# @ImageDisplay image
# @ImageJ ij
# @ImagePlus im

from ij import ImagePlus

imp = ij.convert().convert(data, ImagePlus)

# Do nothing
imp.setZ(3);

# Work and change the Z position on the image display
im.setZ(3);
```

**Comment by hadim** [comment]
My workaround is to use `ij.IJ.getImage();` but I don't really like it.

**Comment by imagejan** [comment]
> `imp = ij.convert().convert(data, ImagePlus)`

You're creating a new ImagePlus instance here. If you show() it, it seems to work fine:

```
imp.setZ(3)
imp.show()
```

**Comment by hadim** [comment]
Ok. Thanks for the precision, I didn't know that. Do you know if it's possible to get the `Imageplus` corresponding to a `Dataset` (the one that is displayed by the IJ1 interface) without using `imagej-legacy` ?

**Comment by hinerm** [comment]
> Do you know if it's possible to get the Imageplus corresponding to a Dataset (the one that is displayed by the IJ1 interface) without using imagej-legacy ?

No, `imagej-legacy` is **the** component for synchronizing `Dataset` and `ImagePlus`.

But, you have an `ImagePlus` parameter:

> # @ImagePlus im

so isn't that sufficient? Can you explain more about why you want to convert at all?

**Comment by hadim** [comment]
Ok I just didn't know about that. `ImagePlus` parameter is fine and I will use this. Thank you !
