### ISSUE TITLE
Add ResultsTable input parameter

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#155]
Sometimes it can be useful to get the current `ResultsTable` from ImageJ for use in a script.

Instead of:
```groovy
import ij.measure.ResultsTable
rt = ResultsTable.getResultsTable()
```

I'd like to simply be able to write:
```groovy
// @ResultsTable rt
```

Where would be the appropriate place to wrap this?

**Comment by ctrueden** [comment]
@imagejan I added this feature in 7af335206959912fefa5ddd9c83258270bbbfa42. If you have any other IJ1 classes you would like to support as parameters, you can model such PRs after this branch. Cheers.
