### ISSUE TITLE
Avoid recording auto-populated singleton parameters in macros

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#170]
Currently, the macro recorder records something like:

```
run("My Command", "platformservice=[org.scijava.platform.DefaultPlatformService [priority = 0.0]]");
```

and similar parameters when running a script the has Services and other singletons in its parameter list.
I suggest to stop recording these singleton parameters, at least when recording in IJ1 Macro mode.

**Comment by ctrueden** [comment]
This did not used to be the case. I am guessing it is a bug introduced when we changed how service parameters are populated internally. It is very likely solvable by changing the priority of the `MacroPreprocessor` to be slightly lower than `ServicePreprocessor`, instead of exactly the same (which makes the preprocessing order undefined). We can use the new `Priority` constants, which have a higher granular, so that we no longer need to write `2 * VERY_HIGH` anymore.

**Comment by imagejan** [comment]
I don't think the issue is caused by wrong priorities of `MacroPreprocessor`. IIUC, the `MacroPreprocessor` is responsible for processing input parameters when a command is *called* from a macro. To be clear, there's no problem with leaving out service parameters when calling from a macro: the singletons get populated correctly even if not present in the macro option string.

However, this issue is about *recording* macro commands, where these parameters get recorded although it shouldn't be necessary to specify them.
So I guess we should edit [`MacroRecorderPostprocessor`](https://github.com/imagej/imagej-legacy/blob/master/src/main/java/net/imagej/legacy/plugin/MacroRecorderPostprocessor.java) accordingly to ignore Service and other Singleton parameters.

**Comment by ctrueden** [comment]
Doh! Sorry for steering you wrong there.

> So I guess we should edit `MacroRecorderPostprocessor` accordingly to ignore Service and other Singleton parameters.

I guess so. But it's a little tricky deciding what to edit out, in general.

One strategy could be to have a linked preprocessor that notes which parameters are already resolved at some early point in the pipeline. Then the postprocessor excludes those parameters in its output.

**Comment by stelfrich** [comment]
Thank you @ctrueden!
