### ISSUE TITLE
Script parameters are wrongly excluded from/included in recording

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#194]
See [this forum post](http://forum.imagej.net/t/script-parameters-in-macro-recorder-issue/2527/10?u=imagejan) and commit https://github.com/imagej/imagej-legacy/commit/6ee7a3cf9ff149e55cbb8e1c4125a7a4e2611dae where it got mixed up.

**Comment by ctrueden** [comment]
Arrrgh. Sincere apologies for that!

**Comment by ctrueden** [comment]
Ideally, I should have added a unit test proving that this feature works as intended. It would have caught this regression in the first place. But there are too many other critical bugs to fix right now, so the technical debt continues!

If you get a chance, please test the new snapshot and report back if it things are still broken.

**Comment by imagejan** [comment]
So this issue translates into "add a unit test" now. :slightly_smiling_face: If you give me some hint how we can test the actual recording when running headless during maven tests, I might try to set one up.

**Comment by ctrueden** [comment]
Sorry, but it was not something I could give any quick hint about. It is complicated; to understand it, I had to dig in and figure it out myself. See 5cf3fd827bffac7a82804b332d93082d50e2f230.
