### ISSUE TITLE
Reported line numbers are wrong for IJ1 Macro scripts

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#197]
When running an IJ1 Macro script containing an error, the reported line numbers are off by 1+the number of script parameters. Likely an issue with the script pre-processing, but specific to the IJ1 macro language.

Test scripts:
```
x = nonExistent
```
(error reported to be in line 2)

---

```
#@ String (required=false) text1
#@ String (required=false) text2

x = nonExistent
```
(error reported to be in line 7)

**Comment by ctrueden** [comment]
This is a longstanding issue. It happens because in order to inject the parameters into an IJ1 macro, we must physically alter the script to prepend lines, then feed the altered script to IJ1.

In order to fix it, we would need to post-process the error message to parse the line numbers and adjust them accordingly.

**Comment by imagejan** [comment]
Would it help to factor out the additional lines into a macro function, append it to the _end_ of the macro (similar to how ImageJ1 does it with [additional functions](https://github.com/imagej/imagej1/blob/a750ce0ed717ce2cccb7a07cbc96b1a2394a68ff/ij/macro/Interpreter.java#L78-L83)), and then only call this function in a single prepended line? This would at least reduce the offset of the reported line number to be always one, instead of increasing with the number of script parameters present.

**Comment by ctrueden** [comment]
Interesting idea! But I do not think it would work; I tested the following:
```javascript
injectParameters();
print(greeting + ", " + name + "; x=" + x);
function injectParameters() {
	x = 1;
	name = "Curtis";
	greeting = "Hello";
}
```
And it gives the error:
```
Undefined variable in line 3:
print ( <greeting> + ", " + name + "; x=" + x ) ; 
```
Does the macro language have a way to define a variable with global scope from within a function?

**Comment by imagejan** [comment]
Oh, yes, I forgot about variable scope. We really miss the `goto` command in the macro language ;-D

The following works, but is useless indeed:

```javascript
var x; var name; var greeting; injectParameters();
print(greeting + ", " + name + "; x=" + x);
function injectParameters() {
	x = 1;
	name = "Curtis";
	greeting = "Hello";
}
```

---

> But I think this cannot happen, because the #@ ... line will be replaced with `` and thus the first (blank) line will never have errors.

It still can happen if the _newly inserted_ lines contain errors (or, in case we add everything in the beginning of the first line, also if the first line contains errors).

**Comment by imagejan** [comment]
I tried using this pattern for parameter initialization (see https://github.com/imagej/imagej-legacy/commit/b7bc93a89ad3f669d69be36d7d5125707f21f22b):

```
var x, name, greeting; initializeSciJavaParameters();
print(greeting + ", " + name + "; x=" + x);
function initializeSciJavaParameters() {
	x = 1;
	name = "Curtis";
	greeting = "Hello";
}
```

but it turns out that the bindings do not work when variables are declared global with the `var` statement in the macro language: `IJ1MacroLanguageTest.testBindings` is failing with the commit linked above.

**Comment by imagejan** [comment]
It turns out the global variables were not correctly parsed: in the `String []` array returned by `getVariables()`, the variable names contain a " (g)" suffix when they're global. Removing that suffix when present fixes the bindings.

The tests now pass, and the line numbers reported by _Macro Error_ dialogs are now correct.

I noticed that in the _Debug_ window, you can still see all values of variables, even when declared with `style=password`, but this was the case before this fix, and it might also be the desired behavior, as we expect to see all values when debugging, right?

**Comment by ctrueden** [comment]
> It still can happen if the newly inserted lines contain errors (or, in case we add everything in the beginning of the first line, also if the first line contains errors).

What is the advantage of creating a function at the end of the macro, versus simply declaring all variables with assignments at the beginning of the first line? Either way, we have to modify the first line of the macro to include some extra characters.

**Comment by imagejan** [comment]
> What is the advantage of creating a function at the end of the macro, versus simply declaring all variables with assignments at the beginning of the first line? Either way, we have to modify the first line of the macro to include some extra characters.

The advantages would be:
* we can keep modifications to the first line as short as possible (only variable names, no values)
* the error message dialog would not contain any (potentially confidential) information about passwords etc. (although the debug window would still do)
* the `call("net.imagej.legacy.plugin.IJ1MacroEngine.saveInterpreter");` line would also be hidden from the error message dialog.

**Comment by ctrueden** [comment]
@imagejan Great, I understand now, and am convinced of the approach. I merged it.
