### ISSUE TITLE
IJ2 commands returning Dataset/Img don't work with setBatchMode(true) in macros

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-legacy#215]
Consider the following macro, using the *File > Import > Image...* command:

```javascript
#@ File input
setBatchMode(true);
run("Image... ", "source=[" + input +"] crop=false autoscale=true computeminmax=false x=0 y=0 w=0 h=0 groupfiles=false mode=Auto range=0");
run("Z Project...", "projection=[Max Intensity] all");
setBatchMode("show");
```

This will throw and error:

> There are no images open in line 4

Changing line 2 to `setBatchMode(false);` makes it work as expected.

I guess the issue is that `Dataset` objects are not (or too lazily) synced with IJ1 `ImagePlus`es.

**Comment by hinerm** [comment]
Note that despite the fix this won't work running headlessly currently.
