### ISSUE TITLE
Get rid of the 'legacy mode'

### ISSUE THREAD

**Issue by dscho** [imagej/imagej-legacy#22]
The legacy mode (i.e. switching off all synchronization between legacy ImageJ 1.x and the ImageJ2  context) was a nice way to be able to switch Fiji to ImageJ2 gradually. However, after ImageJ 2.0.0 will be released, it will be the time to clean up all the synchronization issues (in particular the performance thereof) so that we do not need the legacy mode any longer, no matter whether we're displaying the legacy UI or the modern one.

**Comment by ctrueden** [comment]
The mode-switching plugins have been removed as of 693fdd4608a31113893c10896a67dec40598a1d3. We'll be sticking with the ImageJ 1.x user interface at least for the medium term.
