### ISSUE TITLE
ImageJ 1.53h breaks line bounds

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-legacy#279]
```
$ mvn -Dij1-patcher.version=1.2.2 -Dij.version=1.53h
...
[ERROR] Failures:
[ERROR]   DefaultRoiConversionTest.testDefaultRoiWrapperLineWithWidth:109 expected:<100> but was:<101>
[ERROR]   IrregularPolylineRoiWrapperTest.testIrregularPolylineRoiWrapperFreelineWithWidth:136 expected:<188.25> but was:<189.25>
[INFO]
[ERROR] Tests run: 260, Failures: 2, Errors: 0, Skipped: 0
```
Caused by [this change](https://github.com/imagej/ImageJ/commit/fa8bee728#diff-e875a7c49a0f14f36b8403902ab0134788e213238c3ac4292ef8a072814cd670R34) i.e. [this version of `Line.java`](https://github.com/imagej/ImageJ/blame/fa8bee728ad3204480717d0897cf9170d8b666bc/ij/gui/Line.java#L34).

More investigation needed to understand the details, but looks like a new bug in ImageJ as of v1.53h. One would expect the max coordinate of lines to be `(r.x + r.width, r.y + r.height)` but it seems the logic is now off by one.

**Comment by rasband** [comment]
Where can I find the source code for DefaultRoiConversionTest and IrregularPolylineRoiWrapperTest?

**Comment by ctrueden** [comment]
Thanks @rasband for being willing to look at it. I didn't want to report a bug in ImageJ until I knew more about the problem, and I ran out of time to dig, hence this issue.

The code in question is here in this imagej-legacy repository:
* https://github.com/imagej/imagej-legacy/blob/729751bf7f8a198e363ef0f8181d68a99e47f0bb/src/test/java/net/imagej/legacy/convert/roi/DefaultRoiConversionTest.java#L100-L110
* https://github.com/imagej/imagej-legacy/blob/729751bf7f8a198e363ef0f8181d68a99e47f0bb/src/test/java/net/imagej/legacy/convert/roi/polyline/IrregularPolylineRoiConversionTest.java#L132-L136

And the `DefaultRoiWrapper`:
* https://github.com/imagej/imagej-legacy/blob/729751bf7f8a198e363ef0f8181d68a99e47f0bb/src/main/java/net/imagej/legacy/convert/roi/DefaultRoiWrapper.java#L74-L99

It calls `r = roi.getBounds()` and then reports the max as `r.x + r.width` and `r.y + r.height` respectively, which used to match expectations, but now is off by one as shown above. I briefly looked at the changes to `Line` linked above, but didn't fully understand the consequences of the `+ 0.5` change, or even if that was for sure what causes this change in behavior.

We could change the tests here in imagej-legacy so they pass, but it feels wrong for the max to be off by one, when the x1/y1/x2/y2 use `double` and are therefore not necessarily in integer space.

Any insight you could provide would be very helpful.

**Comment by rasband** [comment]
There is a bug with getBounds() when used with point selections. It creates a rectangle that is one pixel wider and taller than expected.

Here is example that reproduces the problem:

```
  newImage("Untitled", "8-bit ramp", 50, 50, 1);
  run("Add Noise"); //makes the pixels visible
  makePoint(10, 10);
  setKeyDown("shift");
  makePoint(11, 10);
  Roi.getBounds(x, y, width, height);
  print("integer bounds: ",x, y, width, height);
  run("Add Selection...");
  makeRectangle(x, y, width, height);
  run("To Selection");
```

**Comment by rasband** [comment]
The ImageJ 1.53s31 daily build fixes the bug that caused getBounds() to return a rectangle one pixel wider and taller than expected with point selections.

The following test macro reproduces the problem. It aborts with the error message "contains() test failed" with versions of ImageJ earlier than 1.53h.

```
  newImage("Points", "8-bit noise", 50, 50, 1);
  xp = newArray(7,8,9,10,8,8,7);
  yp = newArray(7,6,7,9,10,8,9);
  makeSelection("point large red dot", xp, yp);
  Roi.getBounds(x, y, width, height);
  run("Add Selection...");
  makeRectangle(x, y, width, height);
  run("To Selection");
  for (i=0; i<xp.length; i++) {
     if (!selectionContains(xp[i], yp[i]))
        exit("contains() test failed");
  }

```
![Screenshot](https://user-images.githubusercontent.com/1633637/168307679-45a9cd0a-a859-4060-929f-d69c2c792365.png)
