### ISSUE TITLE
Search results: legacy commands give invalid URL

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#291]
The `Help` button attached to ImageJ 1 plugins in the search results currently links to `imagej.net/[Plugin_Name]`
![image](https://user-images.githubusercontent.com/1123809/227262344-4be9ff82-418a-4782-8914-ba39c4be1c6f.png)

This leads to a `404`:
![image](https://user-images.githubusercontent.com/1123809/227262409-044e8b83-3bc6-433b-a0e8-bf0aa72cf67b.png)

I think this should link to an `https://imagej.nih.gov` link but there are many options. In my preferred order:
1. https://imagej.nih.gov/ij/docs/menus/[appropriate_menu.html]
2. https://imagej.nih.gov/ij/docs/](https://imagej.nih.gov/ij/docs/
3. https://imagej.net/libs/imagej-legacy

I'm open to other suggestions of course.

**Comment by elevans** [comment]
Don't we host legacy ImageJ at https://imagej.net/ij/index.html now? Why not use that?
