### ISSUE TITLE
ImageJ Forum search bar entries give 403

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#294]
If I click the "Forum" button from the search bar:
![image](https://user-images.githubusercontent.com/1123809/232143487-cb0524a6-51bc-41fd-95fc-25f4e2b68587.png)

I just get this error:
![image](https://user-images.githubusercontent.com/1123809/232143402-9dfadf02-bb08-4fa1-aee5-0b818d9ca8b9.png)

Manually navigating [to the URL](https://forum.image.sc/search/query.json?term=threshold+tags%3Aimagej) appears to give an appropriate json response.

**Comment by ctrueden** [comment]
Duplicate of scijava/scijava-search#29 ?

**Comment by hinerm** [comment]
> Duplicate of [scijava/scijava-search#29](https://github.com/scijava/scijava-search/issues/29) ?

Looks like it
