### ISSUE TITLE
Ensure CI is running on all platforms

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#309]
ImageJ-Legacy is a sensitive component. Given recent issues like https://github.com/imagej/imagej-legacy/issues/305 and https://github.com/imagej/imagej-legacy/issues/306 we should ensure that our tests are running on all platforms

**Comment by imagejan** [comment]
It seems the Maven build isn't actually running on Windows:
https://github.com/imagej/imagej-legacy/actions/runs/10066110644/job/27826724022

Maybe adding `shell: bash` to the "Execute the build" step would help?
